### ISSUE TITLE
Inputting dictionary to model.set_calibration

### ISSUE THREAD

**Issue by msilva913** [EconForge/dolo#129]
Hi:

From looking at the documentation, I thought one could input a dictionary into model.set_calibration. But whenever I try to do so, I get a TypeError:
``
ipdb> model.set_calibration({'phi':0.2})
*** TypeError: set_calibration() takes 1 positional argument but 2 were given
``
Is there a reasonable way to correct the syntax, or is some package potentially out of date? I wanted to apply this for different parameters where I entered a string.

**Comment by albop** [comment]
Try unpacking the didctionary: model.set_calibration(**{'phi':0.2}) which
is equivalent to model.set_calibration(phi=0.2)
Don't close the issue. There is no reason we shouldn't accept a dictionary
here.
