### ISSUE TITLE
Solow Model?

### ISSUE THREAD

**Issue by spring-haru** [EconForge/dolo#131]
Is it possible to do a simulation of the Solow model, stochastic or deterministic? I tried, but could not figure it out.

**Comment by pkofod** [comment]
> Is it possible to do a simulation of the Solow model, stochastic or deterministic? I tried, but could not figure it out.

can you post your attempt at producing a correct model specification? Might make it easier to point out the mistakes.

**Comment by spring-haru** [comment]
After asking the question, I ended up with the following code, which seems working. Can you suggest how to improve upon it?


```
name: Solow Model

symbols:

   exogenous: [e]
   states: [k, z]
   controls: [s]
   parameters: [A, l, delta, alpha, rho, s_fixed, zbar, sig_z]

definitions:
    y: A*exp(z)*k^alpha*l^(1-alpha)
    i: s * y
    c: y - i
    r: alpha*y/k
    w: (1-alpha)*y/l

equations:

    arbitrage:
        - s = s_fixed

    transition:
        - k = (1-delta)*k(-1) + i(-1)
        - z = rho*z(-1) + e

calibration:
    # parameters
    A : 1
    s_fixed : 0.1
    l : 1.0
    delta : 0.025
    alpha : 0.33
    rho : 0.9
    sig_z: 0.2
    zbar: 0
    e: 0.0
    # steady states
    z: zbar
    s: s_fixed
    k: l*(s*exp(z)/delta)^(1/(1-alpha))
    y: A*exp(z)*k^alpha*l^(1-alpha)
    i: s*y
    c: y - i
    r: alpha*y/k
    w: (1-alpha)*y/l

exogenous: !Normal
    Sigma: [[sig_z**2]]

domain:
    z: [-3, 3]
    k: [ k*0.5, k*1.5]

options:
    grid: !Cartesian
        n: [10, 50]
```

**Comment by albop** [comment]
What is it that you want to improve if it is working ?
I can see how dolo could be improved to avoid solving a model, where the
controls are given in closed form. Also, in this case, the exogenous shock
is irrelevant, so we should ensure, it still works without shock or zero
variance. But that sounds more like dolo issues. To me, your model file is
perfectly fine.
