### ISSUE TITLE
ImportError: cannot import name 'ols'

### ISSUE THREAD

**Issue by iworld1991** [EconForge/dolo#132]
when I run 

"from dolo import * " in my Ipynb environment I got following errors :

- ImportError: dateutil 2.5.0 is the minimum required version. 
- ImportError: cannot import name 'ols'

**Comment by albop** [comment]
that is strange. Can you give us more details about your python environment ? (python version, conda/pip, windows/linux, ...)

**Comment by iworld1991** [comment]
Hi, my python enviroment is following:

"Python 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) "

"conda 4.5.11"

thanks

**Comment by sglyon** [comment]
Could you also post the entire traceback?

I remember seeing these errors are few years ago with a very out of date pandas (I'm thinking in the 0.16 range)

posting the whole traceback would let us sort this out

**Comment by albop** [comment]
Yes, I agree with @sglyon, it's certainly a pandas version issue, not necessarly a very old version though. You should update all packages, including pandas and dateutil.
But then, dolo assumes python >= 3.6 (for sorted dictionaries among other things) so you'll probably need another anaconda distribution.

**Comment by iworld1991** [comment]
Thanks for your responses. I do think it has to do with pandas version. I have tried updated my conda distribution to the most recent. Also upgrade the pandas and etc. 

This is my conda information:
    conda version : 4.5.11
    conda-build version : 1.18.2
    python version : 3.5.3.final.0

This is the full trace-back history of the error 
```

```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7c1e6ea9bebd> in <module>()
----> 1 from dolo import *

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/__init__.py in <module>()
     10 from dolo.misc.dprint  import dprint
     11 
---> 12 from dolo.algos.commands import *

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/algos/__init__.py in <module>()
      1 __author__ = 'pablo'
      2 
----> 3 from .commands import *

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/algos/commands.py in <module>()
      1 # this is for compatibility purposes only
      2 
----> 3 from dolo.algos.time_iteration import time_iteration
      4 from dolo.algos.simulations import simulate, response, tabulate, plot_decision_rule
      5 from dolo.algos.value_iteration import evaluate_policy, value_iteration

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/algos/time_iteration.py in <module>()
      1 import numpy
      2 from dolo import dprint
----> 3 from dolo.numeric.processes import DiscretizedIIDProcess
      4 from dolo.numeric.decision_rule import DecisionRule
      5 from dolo.numeric.grids import CartesianGrid

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/numeric/processes.py in <module>()
      9 # should be moved to markov
     10 from numba import jit, njit
---> 11 from dolo.numeric.grids import EmptyGrid, CartesianGrid, UnstructuredGrid
     12 
     13 @njit

/Users/Myworld/anaconda/lib/python3.5/site-packages/dolo/numeric/grids.py in <module>()
      1 from functools import reduce
      2 from operator import mul
----> 3 from quantecon import cartesian
      4 import numpy as np
      5 from numpy import zeros

/Users/Myworld/anaconda/lib/python3.5/site-packages/quantecon/__init__.py in <module>()
     11 from .discrete_rv import DiscreteRV
     12 from .ecdf import ECDF
---> 13 from .estspec import smooth, periodogram, ar_periodogram
     14 from .graph_tools import DiGraph
     15 from .gridtools import cartesian, mlinspace

/Users/Myworld/anaconda/lib/python3.5/site-packages/quantecon/estspec.py in <module>()
     11 import numpy as np
     12 from numpy.fft import fft
---> 13 from pandas import ols, Series
     14 
     15 

ImportError: cannot import name 'ols'
```
```

**Comment by albop** [comment]
You need python >=3.6

**Comment by iworld1991** [comment]
Thank you. 

Finally, I got it solved. Part of the reason was I could not update my python to the latest recent one although I thought I have achieved it. Now once I reinstall and update everything to the most recent, it worked.

**Comment by albop** [comment]
Perfect! Closing the issue now
