### ISSUE TITLE
ENH: allow for more i.i.d. exogenous shocks

### ISSUE THREAD

**Issue by albop** [EconForge/dolo#145]
We can support any distribution, where it is possible to draw points, and for which there exists a discretization method. We can proceed in several steps:
1. libraries with such methods (scipy, quantecon, hark, distcan)
2. find consistent naming schemes across distributions
3. implement the objects.
First distributions to implement in 3. should be the ones available in HARK (cf https://github.com/econ-ark/HARK/pull/258)

**Comment by albop** [comment]
actually, the package to look for is not distcan but rvlib: https://github.com/QuantEcon/rvlib

**Comment by sglyon** [comment]
rvlib wraps RMath and provides numba-ized routines

Distcan is mostly a wrapper around scipy.stats that provides a reparameteriation of many of scipy's  distributions to the "standard" parameterization and then exposes scipy's methods and a few other helper ones
