### ISSUE TITLE
Python3 install

### ISSUE THREAD

**Issue by yaniv256** [EconForge/dolo#60]
Don't know if it is supposed to go through or not. No problems with the python2 install, but I get an [error](https://gist.github.com/yaniv256/a2c2d59e89da4ffae645) for python3.

**Comment by albop** [comment]
I have looked into it a little bit and pushed a few compatibility fixes. It is not working yet, though. The main problem, is that the definition of the AST is different for Python 2 and Python 3, which complicates a bit the manipulation I do to compile the function (in `dolo/compiler/function_compiler_ast.py`). I need to think carefully about how to deal with that. In the meantime, compatibiblity with Python 3, will be postponed a little bit. Do you need it for something ?

**Comment by yaniv256** [comment]
No I don't need it, just wanted to let you know in case you want it to be compatible. If you don't support Python 3 it would be good to let people know in the install section.

**Comment by yaniv256** [comment]
In addition, there must be some users where `pip install` maps to `pip3 install` and they don't even know it. Maybe we should instruct people to do `pip2 install` if we know `pip3` is bound to fail.

**Comment by albop** [comment]
This one should be fixed now, with the latest compatibility commit.
