### ISSUE TITLE
sparse grid prediction poor

### ISSUE THREAD

**Issue by denfromufa** [EconForge/dolo#69]
I followed the example in this page:

http://www.econforge.org/dolo/_modules/dolo/numeric/interpolation/smolyak.html

First of all, the latest code does not correspond to this sample.

```
#bounds = numpy.array([
smin=    [ -1, -1 ]   # lower bounds
smax=    [ 1, 1 ]   # upper bounds
#])
```

Some of the arrays in the code have to be transposed.

Then the interpolation is very poor:

Maximum error : 27.0671814924 when smolyak parameter is 3

Maximum error : 9.05216715903 when  smolyak parameter is 5

**Comment by denfromufa** [comment]
here is complete code:

```
#bounds = numpy.array([
smin=    [ -1, -1 ]   # lower bounds
smax=    [ 1, 1 ]   # upper bounds
#])

sg = SmolyakGrid(smin,smax, 5)  # 3 is the smolyak parameter l

print(sg.grid.shape)

import matplotlib.pyplot as plt
%matplotlib inline
sg.plot_grid()


fun = lambda x,y: numpy.exp( -numpy.power(x,2) - numpy.power(y,2) )
values_on_the_grid = fun( sg.grid[:,0], sg.grid[:,1] )

sg.set_values(values_on_the_grid)

from  numpy.random import multivariate_normal as  mvtnorm
mean = numpy.zeros(2)
cov = numpy.eye(2)
s = mvtnorm(mean,cov,50)

interpolated_values = sg.interpolate( s )

true_values = fun(s[:,0], s[:,1])

max_error = abs( true_values - interpolated_values[:,0] ).max()

print( 'Maximum error : {}'.format(max_error) )

print s.shape
print interpolated_values.shape
print true_values.shape
print 'max val:',
print max(true_values)
plt.scatter(true_values,interpolated_values[:,0])
plt.xlim([0,1])
plt.ylim([0,1])
```

**Comment by albop** [comment]
Thank you for reporting this.
I see two potential issues with the code
- the instruction `sg.set_values(values_on_the_grid)` expect the argument to be a `Nx1` matrix. In the example you give, values_on_the_grid is a `N` vector, which, following conventions should be represented as a `1xN` array. (this is the result of `numpy.atleast_2d` ). Apparently, the method converts it automatically to a `Nx1` but I am not sure whether it is a good feature to keep or not.
- the points at which you evaluate the smolyak polynomials are generated randomly and clearly some of them will lie outside of the definition space where those polynomials are known to perform badly. If you restrict the points using something like `s = numpy.minimum(1, numpy.maximum(-1, s))` you should have better results.

**Comment by albop** [comment]
By the way, the plan is to exfiltrate the interpolation routine from the dolo package into another one, focused only on interpolation: https://github.com/EconForge/interpolation.py . It has new smolyak routines, that are not feature equivalent yet, but are more efficient when constructing grid, with large number of dimensions.

**Comment by denfromufa** [comment]
I found 4 smolyak grids in web, is there any difference between them?

http://people.sc.fsu.edu/~jburkardt/py_src/sparse_grid/sparse_grid.html

https://aerodynamics.lr.tudelft.nl/~rdwight/work_sparse.html

https://pypi.python.org/pypi/puq/2.2.1

http://rncarpio.github.io/py_tsg/
