### ISSUE TITLE
Bug in spline interpolate?

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/dolo#78]
I suspect that there is a bug [here](https://github.com/EconForge/dolo/blob/master/dolo/numeric/interpolation/splines.py#L102). 

Notice that the 2d array is transposed.

I found this issue trying to call from `dolo.algos.dtcscc.accuracy.omega` on a spline decision rule and noticed that if I remove the transpose on this line everything goes through without a problem. Also in the interpolation.py package the transpose [doesn't seem to be there](https://github.com/EconForge/interpolation.py/blob/master/interpolation/splines/splines.py#L122).

**Comment by albop** [comment]
Right. When evaluated at à vector, atleast_2d produces à matrix with one
row (which is what we want)
