### ISSUE TITLE
ENH: improve perfect foresight experience

### ISSUE THREAD

**Issue by albop** [EconForge/dolo#82]

**Comment by albop** [comment]
There is a working version of the RMT1191 example in the `pf_example` branch. Notebook and yaml files: https://github.com/EconForge/dolo/blob/pf_example/examples/notebooks/Figures1191_1193%28dolo%29.ipynb and https://github.com/EconForge/dolo/blob/pf_example/examples/models/Figv4_1191.yaml )

The goal of this issue is to list things that feel unnatural and could be improved. Here are a few propositions (the last two ones have been on the agenda for a while):
- the yaml file: one must define a dummy covariance matrix, although it is completely useless here
- cell 2: the exogenous shock must by supplied as a 101 (length of simulation) times 1 (number of shock variables) array. Would it be safe to autodetect this situation and promote a 101 vector into the right array ?)
- cells 3 and 4: the distinction between the two dictionaries representing the steady-state (one containing vectors, the the containing values) is tedious. Maybe it would be a good idea to define a calibration object that would behave like both model.calibration and model.calibration_dict . Again, would there be side-effects ?
- each graph basically compare two or three simulations for specified variable names. There should be a function for that: `plot_irfs(pandas_simulations, variables_or_expressions)` which would produce the desired graphs or at least a convincing first pass. 
- next to last graph computes new series in a pandas dataframe. This could be made easier, while building on dolo's language. In particular, the definition of r_{t,t+1} could be made by something like: `sol['q'] = model.eval_sim(sol, 'beta**n*c**(-gamma)/(beta**2*c(S)**(-gamma)))')` and then `sol['ret'] = model.eval_sim(sol, 'log(q)/log(q(-1)/t')`

**Comment by spencerlyon2** [comment]
I think there is a bug [here](https://github.com/EconForge/dolo/blob/16cae42f22a0e2de9b19b6ff566e03db07ff5b64/dolo/algos/dtcscc/perfect_foresight.py#L155-L156)

Notice that when computing `final_calib` we pass `start_dict` instead of `final_dict`

**Comment by albop** [comment]
Yes, that is indeed a bug. It should have no effect most of the time though as this is just used as a initial guess.

**Comment by albop** [comment]
There is now an implementation for all the points above.
The last one raises a few issues for the upcoming language overhaul. Ideally one would want an notation for time `t` (currently `v`) and time `t+1` (currently `v(1)`) but also for the steady-state value `\overbar{v}` (temporarly `v_ss`) and the value at any period of time (  `v[1]` ? not implemented )

**Comment by albop** [comment]
Another question is whether we want to keep `deterministic_solve` for the solution method or change to something like `perfect_foresight`.

**Comment by spencerlyon2** [comment]
Great work! Thank you for working through this

I think the changes over the past few days make the experience for doing these perfect foresight simulations much more pleasant. 

I'm looking forward to the discussion on the language overhaul.

Regarding naming, I think that both names are appropriate. I'm indifferent between the two.
