### ISSUE TITLE
Cleanup the qz code

### ISSUE THREAD

**Issue by albop** [EconForge/dolo#88]
It still relies on some old ctypes wrapper by Sven Schreiber.
The reordering routines in lapack seem complicated to wrap because of the need to send callback routines (selectg). The medium run equilibrium could be:
- get rid of all ctypes
- call the non-reordering routine in scipy
- numbaify qzswitch
- use qzswitch to write a new reodering function with several options

An alternative for the last point would be to use the current code which reorders based on a threshold value.

**Comment by albop** [comment]
Gone for a slightly different plan:
- now calling scipy.linalg.ordqz to do the factorization and the reordering
- temporarily duplicating some of the scipy code until https://github.com/scipy/scipy/pull/6044 is merged

Numbaification of ordqz won't happen in the short run as one would need to pass a c pointer to a 
function.

Numbaify qzswitch is still an option, but one would need to assess the potential benefits (not clear there are).

**Comment by spencerlyon2** [comment]
I'm glad to see that scipy is fixed (or will be soon).

Except for the fact that this blocks us from calling ordqz in a nopython environment, this sounds great. 

Are we ready to close the issue?

**Comment by albop** [comment]
Fixed here: 21b8f4bb3e018c05a76ce336f2da7715afababcd
