### ISSUE TITLE
Error message : Model type detected as 'dtcscc' invalid syntax

### ISSUE THREAD

**Issue by zlqs1985** [EconForge/dolo#89]
Hi, when I was exercuting one line of rbc_model.yaml, an error occured.

```
In[4] : model = yaml_import(filename)
Model type detected as 'dtcscc'
  File "C:\Users\zhanglu\Anaconda2\lib\site-packages\dolo\compiler\function_compiler.py", line 45
    def __call__(self, *args, diff=False, out=None):
                                 ^
SyntaxError: invalid syntax
```

What's the source of my problem and how to fix it , thank you.

**Comment by albop** [comment]
The error probably comes the fact that you are using Python 2.x. Anyway you can try with python 3.5 ?

The construct:
```
def __call__(self, *args, diff=False, out=None):
```
unpacks one positional argument (`*args`)  before keyword arguments. This is now allowed in 3.x but wasn't formerly.

**Comment by zlqs1985** [comment]
I use anaconda2, so I'll see how to transfer to anaconda3, thanks @albop

**Comment by zlqs1985** [comment]
Well , as I create a new working environment of python 3.4 within anaconda2
```
conda create -n py3 python=3.4
source activate py3
conda install notebook ipykernel
ipython kernel install
```
and then `pip install dolo`, however, error occured
```
ImportError : No module named 'numpy'
"python setup.py egg_info" failed
```

see [my question](http://stackoverflow.com/questions/36528525/python-setup-egg-info-failed-when-install-package-in-new-environment) on stack flow for details. Any suggestion to slove this problem?

**Comment by cc7768** [comment]
You never installed `numpy` (or any other dependencies) when you created your new environment. I also would probably suggest Python 3.5 instead of 3.4.

Try the following

```
conda create --name dolopy anaconda
source activate dolopy
ipython kernel install
pip install dolo
```
^This installs all packages that are included in the `anaconda` distribution by default for python 3.5. Activates this environment. Installs the new ipython kernel. Finally installs `dolo`.

Then try the same example and post the issues you run into

**Comment by albop** [comment]
@cc7768 : thank you for answering this question so quickly !
@zlqs1985: don't hesitate to come back with more question. We'll keep this issue open until your installation succeeds.

**Comment by zlqs1985** [comment]
Hi，@cc7768, thanks for suggestion and I followed your instruction, and I also install numpy using conda install numpy. Unfortunately, some errors still occured, like
![1](https://cloud.githubusercontent.com/assets/10328230/14431829/0b21c974-003a-11e6-9176-ddc26182812c.jpg)

![2](https://cloud.githubusercontent.com/assets/10328230/14431837/1560e320-003a-11e6-8a1f-1f295b4d6240.jpg)

and 
![3](https://cloud.githubusercontent.com/assets/10328230/14431812/fc3836a0-0039-11e6-8b18-e7e89fa149aa.jpg)

**Comment by cc7768** [comment]
What version of windows are you running?

This SO question seems possibly relevant: http://stackoverflow.com/questions/28413824/installing-numpy-on-windows . I am surprised that `conda` wasn't able to install `numba` though. Are you able to use `numba` in your default python installation?

**Comment by zlqs1985** [comment]
I‘m running windows10 and I can install dolo on my default anaconda python environment (py2.7).

**Comment by albop** [comment]
@zlqs1985 : Apparently, when you install dolo, llvmite and numba are required and the system tries to install these packages using pip. This suggest that they are not installed in the conda environment. You should install them using `conda`, like you did for `numpy`.
As @cc7768 said, if you do `conda update conda` and `conda install anaconda` you should get all scientific packages at once and not need to repeat that operation for all dependence. 
Otherwise you can repeat the operation `conda install scipy`, `conda install yaml`, `conda install numba` and so on for each missing package.

**Comment by cc7768** [comment]
FWIW, I am not sure that `numba` is installed by default (I actually think it isn't).

@zlqs1985 Try doing `conda install numba` (and like @albop said any other missing packages) before `pip install dolo`

**Comment by zlqs1985** [comment]
@cc7768 ,great, this time I finally did it. One more thing, when testing the .ipynb examples, how should   I let jupyter notebook to exercute under python 3.5 rather than Python 2.7 ？

**Comment by zlqs1985** [comment]
@cc7768 ,great, this time I finally did it. One more thing, when testing the .ipynb examples, how should   I let jupyter notebook (and spyder IDE) to exercute under python 3.5 rather than Python 2.7 ？I first type and then run the .yaml example in spyder IDE, but it seems still exercuted under 2.7.

**Comment by albop** [comment]
Normally, when you create a notebook you have the option of choosing what kernel you want for it. If you open an already existing one, you get a menu item "Kernel/Change Kernel" which allows you to choose Python 3.
As for spyder, I don't use it, but you apparently have an option Preferences > Console > Advanced settings > Use to choose which kernel you use in the ipython console.
I'm a bit surprised that both don't default to python3. Are you running jupyter/spyder from the activated py3 environment ?

**Comment by zlqs1985** [comment]
I made the folder containing dolo example .ipynb file as working directory and then got the python3 worked. However , when exercuting the code, it threw me a different error message.
![2](https://cloud.githubusercontent.com/assets/10328230/14449317/5001113e-00a4-11e6-9747-afc814dedc96.jpg)

**Comment by albop** [comment]
@zlqs1985 : we don't have the bottom of the error message. Are you sure scipy is installed ?

**Comment by zlqs1985** [comment]
@albop , No, I haven't installed `scipy`, I list all package already installed in my environment, so maybe you can kindly check if there is any package I still need. Thanks
![1](https://cloud.githubusercontent.com/assets/10328230/14461800/bb2ed976-00f6-11e6-8ea7-3b38a493f8d0.jpg)
![2](https://cloud.githubusercontent.com/assets/10328230/14461820/d49c56e0-00f6-11e6-9ef5-d9d3a7a28d5b.jpg)

**Comment by spencerlyon2** [comment]
You will need spicy to be installed.

So maybe try `conda install scipy` and try again. I think the original suggestion from @cc7768 was potentially the easiest: just install the entire anaconda suite on a python 3.5 environment.
