### ISSUE TITLE
ENH: parameterized expectations algorithm 

### ISSUE THREAD

**Issue by jagman88** [EconForge/dolo#95]
I would like to add a method to solve for the PEA. A simple version of this can be found in chapter-section 9.9 in the textbook by Miranda and Fackler (2002). 

Essentially, for a rational expectations equilibrium,
`f(s_t, x_t, E_t[h(s_t+1, x_t+1)]) =0`,
we want to approximate the function `h`, rather than the control, `x`. (It would also be possible to approximate the entire expectation, `E_t[h(s,x)]`.)

A sketch of the algorithm is: 
- Guess a function `psi(s)` to approximate the expectation function `h`
- Given `psi(s)`, solve for the control function `phi(s) = x`, by solving `f(s,phi(s),E_t[psi(g(s, phi(s))])=0`, where `g` is the state transition function. 
- Given the control function, `phi(s)`, update the guess for the expectation function: `psi(s) = h(s, phi(s))`. 

I plan to start by working with what's already in the `time_iteration` function. Yaml model files will have to include the `h` function as a definition so that this is known before solving.

Let me know if there's anything else to watch out for ahead of time.

**Comment by albop** [comment]
Sounds good to me @jagman88 .

**Comment by spencerlyon2** [comment]
@albop don't we already have something similar to this that can be used as a starting point?

**Comment by albop** [comment]
@spencerlyon2, there was an open issue, but I closed it to leave space for this new one. @jagman88  is about to do a PR
Also, for a short while time_iteration_direct was called pea, but that was very incorrect.

**Comment by jagman88** [comment]
#### Update:
We now have an algorithm that is _not_ _quite_ the PEA. Rather, it might be better called "parameterized thing-inside-the-expectations-function algorithm", if only that weren't such a long name. I'd coded this up following MF's (2002) section on rational expectation methods. But it seems that this is not exactly what's happening with the PEA described in, for example, den Haan and Marcet (1990). To properly call the method PEA, we'll have to approximate the entire expectation function, ``E_t[h(s_t+1, x_t+1)]`` (rather than just ``h(s_t+1, x_t+1)``). 

Here is the corrected algorithm.  

A sketch of the algorithm is:
- Guess a function ``psi(s)`` to approximate the expectation function ``E_t(h(...))``
- Given ``psi(s)``, solve for the control function ``x = phi(s)``, by solving ``f(s, phi(s), psi( g( s, phi(s)  )])=0``, where ``g`` is the state transition function.
- Given the control function, ``x = phi(s)``, update the guess for the expectation function via: ``psi(s) = E_t[ h(s, phi(s)) ]``.

It shouldn't be too hard to make the fix. However, since the "parameterized thing-inside-the-expectations-function algorithm" is fairly efficient (and slightly faster than time iteration), @albop suggests we keep it and search for a new name. For now, I'm going to rename it "time_iteration_2", but naming suggestions welcome!*


*(Actually, how about the name "PETITE": ParamEterized Thing Inside The Expectations... )
